version: "2"
services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile.app
    command: "bash -c 'bundle && bundle exec ruby generate.rb > sources/zaw-src-emoji.zsh'"
    volumes:
      - .:/zaw-emoji
      - bundle-data:/usr/local/bundle/
volumes:
  bundle-data:
    driver: local
